### PR TITLE
AL

### PR DESCRIPTION
**Pull request by Ryu204**
I implemented 3 concepts: buffer, source and listener. The spirit is the same to the OpenGL wrappers. Currently, the application is capable of playing 3D and 2D sounds alike. However, there are still more things I need to add later to completely wrap the AL API. 

I have a plan for higher-level audio too.

### CODE REVIEW

**Comment by Ryu204** [comment]
Also I still have no idea how to stream music because that require having/implementing a library that periodically loads a sound file.

**Comment by ngoduyanh** [comment]
> Also I still have no idea how to stream music because that requires having/implementing a library that periodically loads a sound file.

You may consider using FFmpeg/libav (LGPL) directly (which basically supports every audio/video formats, but it may cause code bloat (and iirc making a WAV loader from scratch is not that hard).

**Comment by ngoduyanh** [comment]
Personally, I think the current way of uploading data to `SoundBuffer` is somewhat poorly-designed.
- Passing the whole buffer to `ILoader::buffer` is kind of overkill, which could be simplified by only passing the reference to the `Data` struct. This also eliminate the need of having a member `mData` in `SoundBuffer`.
- The way uploading data is working at the moment can be pretty inefficient due to the usage of `vector`, which forces loaders utilizing memory allocated without a `vector` to copy the data. Instead, we can directly upload the data to the buffer without having to copying the data around, and provide some helper functions to make the uploading process easier (The `AudioFile.h` library that you are using is somewhat poorly-designed, so you still have to post-process the data and not being able to avoid this data copy).
- I think you should redesign `ILoader` and `SoundBuffer` like so. `SoundBuffer` would have `bufferData` methods (btw consider remove the `buffer` from the method name, since the object is already a buffer) that purely uploads raw data (and maybe helper functions for specific common formats), and `ILoader` functions can take a `SoundBuffer` (so basically the same API) in the `buffer` function, without any transfer medium (`Data` struct).

(With this design, it would be easier for me to try making a FFmpeg audio loader)

**Comment by ngoduyanh** [comment]
BTW, the `mono16DataBuffer` is clearing the sample data in `mInternalLoader`, so that would make the ILoader not reusable in that specific one case. So considering clearing the data in all other formats, or change that to copy.

**Comment by Ryu204** [comment]
> You may consider using FFmpeg/libav (LGPL)...

I took a look at their [Github mirror](https://github.com/FFmpeg/FFmpeg) but it is pretty confusing to me about which one can we utilize. Can you suggest a bit more specifically?

> (and iirc making a WAV loader from scratch is not that hard)

It's true. But I think finding some well-maintained libraries is better than reinventing the wheel.

About your comments, you said we should remove the medium transferring and push the data loaded from external file to OpenAL directly. Then we clear the remaining data (which has been copied by `alBufferData`) as well, right? I think it's a valid point. I will take a look.

**Comment by btmxh** [comment]
> About your comments, you said we should remove the medium transferring and push the data loaded from external file to OpenAL directly. Then we clear the remaining data (which has been copied by `alBufferData`) as well, right? I think it's a valid point. I will take a look.

Actually this turned out to be a terrible idea, since in the general case, one must concatenate audio data from multiple FFmpeg frames together, making this data copy inevitable.

**Comment by Ryu204** [comment]
Canceling for later PR

**Pull request closed without merging**
