### PR TITLE
Implement DSA lazybind API

### PR DESCRIPTION
**Pull request by btmxh**
don't merge this is WIP

### CODE REVIEW

**Comment by ngoduyanh** [comment]
Test branch is [gfx-test-lazybind](https://github.com/Ryu204/GameFrame/tree/gfx-test-lazybind)

**Comment by ngoduyanh** [comment]
I think this is mergeable now.

**Comment by Ryu204** [comment]
I'm sorry I could not review it carefully (still not knowing that much OpenGL). 

About the name of bound/non-bound types, I would suggest `Boundable{Type}`. It's more concise and as clear.

It's up to you though. I will merge when you reply.

**Comment by ngoduyanh** [comment]
> About the name of bound/non-bound types, I would suggest `Boundable{Type}`. It's more concise and as clear.

The `PossiblyBound...` prefix was inspired from [this](https://docs.rs/glutin/latest/glutin/context/enum.PossiblyCurrentContext.html), but `Boundable{Type}` does not sit right to me tbh (I think the two names have noticeable different grammatical meanings).

**Pull request merged**
