### PR TITLE
 Add many things, including... 

### PR DESCRIPTION
**Pull request by btmxh**
- FFmpeg decoder (and related docs)
- Add `Music` and `Sound` classes (I'd like your opinion on these)
- Make `OpenALWrapper` movable

The only thing left to support audio streaming is a mechanism to
periodically update the music (an audio thread?)

Haven't test this yet, so this may have some issues (especially
audio issues might be able to deafen someone if the volume was too
high).

### CODE REVIEW

**Comment by Ryu204** [comment]
Apologize for my late review.

I think the FFmmpeg parts are really solid and you documented stuff well this time (they worked as intended). Also it's sick we can connect to online urls and get sound data from there.

## FFmpeg:
1. AFAI can tell you are using `std::vector<std::uint8_t>` to hold samples in `LoaderFFmpeg`. Is that also intended for 16-bit samples?
1. OpenAL only supports 2 channels but it seems you convert every multi-channel types to `BufferFormat::Stereo8/16`

## Music:
1. The streaming parts looks nice to me, we will need to test them.
1. There must be a way to configure a source from music stream. I gave it a thought but it's hard. We need to both give means to configure the sound and restricting access to buffer related stuffs (the object must retains the rights to manage buffers). Should we work on this more?
1. Also when I tried to implement streaming, I gave music class an own loader because I see little point to sharing a loader that serves a streaming `SoundSource`. Only benefit I can think of is to reduce the context processing parts.
1. Can u explain this part in `Music.cpp`:
```cpp
if (numProcessed == NUM_BUFFERS) {
  // this is not updated frequent enough
  mSource.play();
}
```	
1. I think `seek` by `sampleIndex` is odd. Like I'm not sure at which scenario will we need it. Of course we will need a functionality that allows us to skip to a specific point using second value, but it's a bit high level and we have not really decided on that. And if your intention is to model a high-level music player that we can put in our game scene, we will needs ways to directly play, pause, and stop a music stream without interfere with source (because multi-threading stuff).

## Sound: 

I don't understand your intention for sounds yet. Are they supposed to be the same sound but allowing multiple emitting locations/directions?

**Comment by btmxh** [comment]
> AFAI can tell you are using `std::vector<std::uint8_t>` to hold samples in `LoaderFFmpeg`. Is that also intended for 16-bit samples?

Yes, it kinda cross a little bit into UB territory it seems, but in most case it should work fine (ffmpeg also store the loaded data in a uint8_t buffer).

**Comment by btmxh** [comment]
> Also when I tried to implement streaming, I gave music class an own loader because I see little point to sharing a loader that serves a streaming `SoundSource`. Only benefit I can think of is to reduce the context processing parts.

Actually you are right in this case. Sharing a loader would even break the streaming process.

**Comment by btmxh** [comment]
> There must be a way to configure a source from music stream. I gave it a thought but it's hard. We need to both give means to configure the sound and restricting access to buffer related stuffs (the object must retains the rights to manage buffers). Should we work on this more?

I intended to let the user have the ability to retrieve a reference to SoundSource and configure using that reference. This level of indirection was supposed to match the API of the `Sound` class, but letting `Music` extend `SoundSource` should be trivial.

**Comment by btmxh** [comment]
> I think `seek` by `sampleIndex` is odd. Like I'm not sure at which scenario will we need it. Of course we will need a functionality that allows us to skip to a specific point using second value, but it's a bit high level and we have not really decided on that. And if your intention is to model a high-level music player that we can put in our game scene, we will needs ways to directly play, pause, and stop a music stream without interfere with source (because multi-threading stuff).

Yeah, I'm designing that like an API of a basic audio player.

I don't get the _we will needs ways to directly play, pause, and stop a music stream without interfere with source_ part though. Is simply using a mutex guard not good enough?

**Comment by btmxh** [comment]
>     4. Can u explain this part in `Music.cpp`:
> 
> 
> ```c++
> if (numProcessed == NUM_BUFFERS) {
>   // this is not updated frequent enough
>   mSource.play();
> }
> ```

Basically, if the condition is true, the source had finished playing sound data in all buffers, which means that the source was not updated frequently enough (to feed more sound data to the buffers and keeping up with the playing process).

**Comment by btmxh** [comment]
> OpenAL only supports 2 channels but it seems you convert every multi-channel types to `BufferFormat::Stereo8/16`

The resample context would resample the audio data into stereo 8/16.

**Comment by btmxh** [comment]
> ## Sound:
> 
> I don't understand your intention for sounds yet. Are they supposed to be the same sound but allowing multiple emitting locations/directions?

Same audio source, its main use is to let many sources at the same time without interrupting each other (if you use one sound source).

**Comment by Ryu204** [comment]
> Yes, it kinda cross a little bit into UB territory it seems, but in most case it should work fine (ffmpeg also store the loaded data in a uint8_t buffer).

I saw this in OpenAL 1.1 specs: 
> *8-bit data is expressed as an unsigned value over the range 0 to 255, 128 being an audio output level of zero.
16-bit data is expressed as a signed value over the range -32768 to 32767, 0 being an audio output level of zero. Byte order for 16-bit values is determined by the native format of the CPU.*

So I think maybe you need to only use Mono8 and Stereo8.

> but letting Music extend SoundSource should be trivial.

You mean extending the whole setter/getter of API of `SoundSource` to Music?

> Is simply using a mutex guard not good enough?

It is, however we won't hand over the private `SoundSource` member to user because that breaks the threading stuff. Then you have to manually provide `play()`, `pause()`, `stop()` in class `Music` which is some works. If you don't like that idea, I am thinking of something like `lendSource()` and `takeSource()` which basically pause/resume the streaming thread for the user to configure using the source reference.

> Same audio source, its main use is to let many sources at the same time without interrupting each other (if you use one sound source).

I think this is a bit specific, and IMO if wanted can be implemented from scratch pretty fast. What I mean is the "wrapping" and extension it does is not too much.

About other answers of you I get them now.

**Comment by btmxh** [comment]
> So I think maybe you need to only use Mono8 and Stereo8.

No, the uint8_t part does not mean the buffer can only hold uint8_t's. Think of it as a vector of bytes. The UB part I mentioned above is about the fact that FFmpeg probably do some pointer casts from `uint8_t*` to `int16_t*` to store the `int16_t` sample data in a`uint8_t*` buffer. I'm not sure if converting from `A*` to `B*` and then use it as `A*` is not UB or not.

**Comment by btmxh** [comment]
> > but letting Music extend SoundSource should be trivial.
> 
> You mean extending the whole setter/getter of API of `SoundSource` to Music?

I saw you let `SoundStream` extends `SoundSource` in the original code, so that's what I assumed what your version of `Music` and `Sound` should behave like. I'm also not advocating for that, just showing that how things could be like in your original design.

**Comment by btmxh** [comment]
> It is, however we won't hand over the private `SoundSource` member to user because that breaks the threading stuff. Then you have to manually provide `play()`, `pause()`, `stop()` in class `Music` which is some works. If you don't like that idea, I am thinking of something like `lendSource()` and `takeSource()` which basically pause/resume the streaming thread for the user to configure using the source reference.

I intended to return a struct like this:
```cpp
struct UsingSource {
    std::unique_lock<std::mutex> SourceGuard;
    SoundSource& Source; // make this weak_ptr or something to make it less unsafe
};
```

Or alternatively, allowing the user to pass in a lambda that takes a `SoundSource&` parameter.

Some side notes regarding your other claims:

We can even avoid pausing the streaming thread by using `try_lock`, which should be done if multiple `Music` instances are playing (or launch a thread every time a `Music` instance is playing, that should be fine for most cases too).

Another important thing is that `Music` breaks a lot of `SoundSource` features (I even documented on not calling `SoundSource::setLoop` in the docs), and when we got an audio thread, that would break `play` and `stop`, since they now both have to register/unregister to the audio thread.

**Comment by btmxh** [comment]
> I think this is a bit specific, and IMO if wanted can be implemented from scratch pretty fast. What I mean is the "wrapping" and extension it does is not too much.

I think overlapping SFX are pretty common in games, it doesn't have much overhead (we are basically giving a simple feature for free), and the user can have the default behavior by letting the number of sources to 1. If every user has to implement stuff like this from scratch, does it kinda defeat the purpose of this project?

**Comment by Ryu204** [comment]
> Another important thing is that Music breaks a lot of SoundSource features (I even documented on not calling SoundSource::setLoop in the docs), and when we got an audio thread, that would break play and stop, since they now both have to register/unregister to the audio thread.

Yeah basically it's not a good solution to give control via the `SoundSource` reference. However I'm more opted for a single thread for every instance of `Music` (though this limits the total number of concurrently streaming instances). It also will not differ much from your idea of single thread for all audio.

> Or alternatively, allowing the user to pass in a lambda that takes a SoundSource& parameter.

I like this idea too. Idk if it's possible to check if a function does change the buffer queue (if yes the lambda is invalid and should be rejected).

> I think overlapping SFX are pretty common in games, it doesn't have much overhead (we are basically giving a simple feature for free), and the user can have the default behavior by letting the number of sources to 1. If every user has to implement stuff like this from scratch, does it kinda defeat the purpose of this project?

I get your point. Maybe it's just because I have never seen this way of engineering before. Yes it will be helpful in many cases now I see.

**Comment by Ryu204** [comment]
Also can you open the PR on `main`? The `al` branch differs quite a bit now.

**Pull request closed without merging**
